
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftMENOSMASleftMULTIDIVrightUNARIODIV MAS MENOS MULTI NUMERO PARA PARC\n    expression : term MAS term\n               | term MENOS term\n    \n    expression : term\n    \n    term : factor MULTI factor\n         | factor DIV factor\n    \n    term : factor\n    \n    factor : NUMERO\n    \n    factor : MAS factor\n           | MENOS factor %prec UNARIO\n    \n    factor : PARA expression PARC\n    '
    
_lr_action_items = {'NUMERO':([0,3,4,7,8,9,12,13,],[6,6,6,6,6,6,6,6,]),'MAS':([0,2,3,4,5,6,7,8,9,10,11,12,13,17,18,19,],[3,8,3,3,-6,-7,3,3,3,-8,-9,3,3,-4,-5,-10,]),'MENOS':([0,2,3,4,5,6,7,8,9,10,11,12,13,17,18,19,],[4,9,4,4,-6,-7,4,4,4,-8,-9,4,4,-4,-5,-10,]),'PARA':([0,3,4,7,8,9,12,13,],[7,7,7,7,7,7,7,7,]),'$end':([1,2,5,6,10,11,15,16,17,18,19,],[0,-3,-6,-7,-8,-9,-1,-2,-4,-5,-10,]),'PARC':([2,5,6,10,11,14,15,16,17,18,19,],[-3,-6,-7,-8,-9,19,-1,-2,-4,-5,-10,]),'MULTI':([5,6,10,11,19,],[12,-7,-8,-9,-10,]),'DIV':([5,6,10,11,19,],[13,-7,-8,-9,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,7,],[1,14,]),'term':([0,7,8,9,],[2,2,15,16,]),'factor':([0,3,4,7,8,9,12,13,],[5,10,11,5,5,5,17,18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> term MAS term','expression',3,'p_expression','parser.py',22),
  ('expression -> term MENOS term','expression',3,'p_expression','parser.py',23),
  ('expression -> term','expression',1,'p_expression_term','parser.py',38),
  ('term -> factor MULTI factor','term',3,'p_term','parser.py',45),
  ('term -> factor DIV factor','term',3,'p_term','parser.py',46),
  ('term -> factor','term',1,'p_term_factor','parser.py',56),
  ('factor -> NUMERO','factor',1,'p_factor_number','parser.py',63),
  ('factor -> MAS factor','factor',2,'p_factor_unario','parser.py',70),
  ('factor -> MENOS factor','factor',2,'p_factor_unario','parser.py',71),
  ('factor -> PARA expression PARC','factor',3,'p_factor_grouped','parser.py',81),
]
